#include <vector>
#include <iostream>
#include <fstream>
#include "employee.h"

using namespace std;

#ifndef __M0070__H__
#define __M0070__H__

// Do not edit this file
void checkArguments( int argc, char **argv );
void openFiles( ifstream &fin, ofstream &fout, char **argv );


bool inputEmployee( istream &in, employee &anEmployee );
void outputEmployee( ofstream &out, vector<employee>::iterator it );

bool compareID( employee &lhs, employee &rhs );
bool compareName( employee &lhs, employee &rhs );
bool compareSalary( employee &lhs, employee &rhs );


#endif