#define CATCH_CONFIG_MAIN
#include "..\catch.hpp"
#include "sortedSingle.h"
#include <sstream>
using std::ostringstream;

/*****************************************************************************
 * do not edit this file
 ****************************************************************************/



